### ISSUE TITLE
Import bnd workspace root project

### ISSUE THREAD

**Issue by paulvi** [osgi/osgi.enroute.site#78]
https://github.com/osgi/osgi.enroute.site/blob/gh-pages/_includes/workspace.md#import-the-bnd-workspace does not import bnd workspace root project

The result is that users have some hidden files, that make system non-transparent, not easy to graspe at first site.

Solution may be putting one `.project` file in https://github.com/osgi/workspace
a general project type would be enough.

**Comment by pkriens** [comment]
The bnd workspace is NOT intending to be an Eclipse project, this likely would confuse the hell out of Eclipse.

Since users are not needing those files until the Continuous Integration (http://enroute.osgi.org/tutorial_base/800-ci.html) I wonder how it would confuse people?

With these tutorials there is always a tension between details and overview. The OSGi enRoute tutorials do explain the details but try to not push it all in ones face from the beginning because that tends to make it harder to understand the other parts.

**Comment by paulvi** [comment]
I think it is good practice to run build from command line and try to run app,
before importing to [Eclipse] IDE
